services:
  - type: web
    name: todo-backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: MONGO_URI
      - key: MAIL_USER
      - key: MAIL_PASS
      - key: SMTP_HOST
      - key: SMTP_PORT
      - key: WHAPI_TOKEN
      - key: GROQ_API_KEY
      - key: OTHER_API_KEYS
